/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-04-01 02:03:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class buy_005fand_005fsell_005fmember_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

String updateValue = "Update Profile";
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      buy.and.sell.BuyAndSell buyAndSell = null;
      synchronized (session) {
        buyAndSell = (buy.and.sell.BuyAndSell) _jspx_page_context.getAttribute("buyAndSell", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (buyAndSell == null){
          buyAndSell = new buy.and.sell.BuyAndSell();
          _jspx_page_context.setAttribute("buyAndSell", buyAndSell, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String isDisabled = "DISABLED";

	String contactNumber = request.getParameter("contact");
	String fbAccount = request.getParameter("fbaccount");

	if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("del ")){
		buyAndSell.deletePost("member", request.getParameter("btn").substring(4));
	} else if(request.getParameter("btn")!=null && (request.getParameter("btn").equals("Update Profile") || request.getParameter("btn").equals("Confirm Update"))){
		if(updateValue.equals("Update Profile")){
			isDisabled = "";
			updateValue = "Confirm Update";
		} else{
			isDisabled = "DISABLED";
			updateValue = "Update Profile";
			buyAndSell.updateProfile(contactNumber, fbAccount);
		}
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").contains("sell")){
		String sellInfo[] = request.getParameter("btn").split("#");
		buyAndSell.itemSold(sellInfo[1], sellInfo[2], sellInfo[3], sellInfo[4]);
	}

	buyAndSell.clearSellerProfile();
	buyAndSell.clearSoldItems();
	buyAndSell.setSoldItems();
	buyAndSell.setSellerProfile();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Buy And Sell</h1>\r\n");
      out.write("\t\t<h3>Welcome, ");
      out.print(buyAndSell.getMemberName() );
      out.write("</h3>\r\n");
      out.write("\t\t<h4>Email Address: ");
      out.print(buyAndSell.getEmailAddress() );
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\t<strong>Contact Number: </strong><input type=\"text\" name=\"contact\" value=\"");
      out.print(buyAndSell.getContactNumber() );
      out.write("\" size=\"");
      out.print(buyAndSell.getContactNumber().length()+2 );
      out.write('"');
      out.write(' ');
      out.print(isDisabled );
      out.write("/> <br />\r\n");
      out.write("\t\t\t<strong>Facebook Account: </strong><input type=\"text\" name=\"fbaccount\" value=\"");
      out.print(buyAndSell.getFbAccount() );
      out.write("\" size=\"");
      out.print(buyAndSell.getFbAccount().length()+2 );
      out.write('"');
      out.write(' ');
      out.print(isDisabled );
      out.write("/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"");
      out.print(updateValue );
      out.write('"');
      out.write('>');
      out.print(updateValue );
      out.write("</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\t<table border=\"2\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"6\">Item List</th>\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>Device Model</th>\r\n");
      out.write("\t\t\t\t\t<th>Date Posted</th>\r\n");
      out.write("\t\t\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\">Action</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					for(int i = 0; i<buyAndSell.getSellerPhones().size(); i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSellerPhones().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSellerDates().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSellerDescription().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSellerPrices().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"del ");
      out.print(buyAndSell.getSellerDates().get(i) );
      out.write("\">Delete Post</button></td>\r\n");
      out.write("\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"sell#");
      out.print(buyAndSell.getSellerPhones().get(i) );
      out.write('#');
      out.print(buyAndSell.getSellerDescription().get(i) );
      out.write('#');
      out.print(buyAndSell.getSellerDates().get(i) );
      out.write('#');
      out.print(buyAndSell.getSellerPrices().get(i) );
      out.write("\">Item Sold</button></td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					} buyAndSell.clearSellerProfile();
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table border=\"2\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"4\">Sold Items</th>\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th>Device Model</th>\r\n");
      out.write("\t\t\t\t\t<th>Date Sold</th>\r\n");
      out.write("\t\t\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					for(int i = 0; i<buyAndSell.getSoldDeviceModel().size(); i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSoldDeviceModel().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSoldDate().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSoldDescription().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(buyAndSell.getSoldPrice().get(i) );
      out.write("</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					} 
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"addnew\">Add New Entry</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"logout\">Log Out</button>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(buyAndSell.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
buyAndSell.setMessage(""); 
      out.write("\t\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
