/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-18 10:48:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addBoarder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

String err= "";  
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      Rent.classes.addClass addBoarder = null;
      synchronized (session) {
        addBoarder = (Rent.classes.addClass) _jspx_page_context.getAttribute("addBoarder", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (addBoarder == null){
          addBoarder = new Rent.classes.addClass();
          _jspx_page_context.setAttribute("addBoarder", addBoarder, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  
	String firstName = request.getParameter("firstName");
	String lastName = request.getParameter("lastName");
	String address = request.getParameter("address");
	String contactNum = request.getParameter("contactNum");
	String email = request.getParameter("emailAdd");
	
	String contactPerson = request.getParameter("contactPerson");
	String contactDetails = request.getParameter("contactDetails");
	
	String roomNum = request.getParameter("roomNum");
	String lockerNum = request.getParameter("lockerNum");
	String dateIn = request.getParameter("dateIn");
	
	String password = request.getParameter("password");
	String password1 = request.getParameter("password1");
	 

	try{
		if (request.getParameter("button").equals("button9")) {
			String message = addBoarder.insert(firstName, lastName, address, contactNum, email, contactPerson, contactDetails, roomNum, lockerNum, dateIn, password, password1);
			if(message.equals("success")){
				err = "Membership successfull";
				addBoarder.setID();
			}else if (message.equals("incorrect")) {
				err = "Your password is incorrect";
			}else {
				err = "error";
			}
			
		}
	} catch(Exception e){
		
	}
	


      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<title>Boarding House Rental System</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"main\" >\r\n");
      out.write("\t\t\t<div id=\"form1\"><hr />\r\n");
      out.write("\t\t\t\t<div id=\"title\"> <h2> BOARDING HOUSE RENTAL SYSTEM </h2> </div> <hr /> <br />\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(err);
      out.write("</h3>\r\n");
      out.write("\t\t\t\t");
err=""; 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"Controller\" method = \"get\">\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<h2>Boarder Information</h2>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">First Name: </label><input type=\"text\" name=\"firstName\" class=\"name1\" Required/> <br><br>\t\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Last Name: </label><input type=\"text\" name=\"lastName\" class=\"name1\" Required/> <br><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Provincial/ City Address: </label><input type=\"text\" name=\"address\" class=\"name1\"  Required/> <br><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Contact No.: </label><input type=\"text\" name=\"contactNum\" class=\"name1\" Required /> <br><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Email Address: </label><input type=\"text\" name=\"emailAdd\" class=\"name1\" /> <br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<h2>In Case of Emergency</h2>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Contact Person </label><input type=\"text\" name=\"contactPerson\" class=\"name1\" Required  /> <br><br>\t\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Contact Details </label><input type=\"text\" name=\"contactDetails\" class=\"name1\" Required /> <br><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<h2>Room Information</h2>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Room Number: </label>\r\n");
      out.write("\t\t\t\t\t<select name=\"roomNum\" class = \"name4\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t</select><br><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\">Locker Number : </label>\r\n");
      out.write("\t\t\t\t\t<select name=\"lockerNum\" class = \"name4\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t</select><br><br>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\"> Date: </label><input type=\"date\" name=\"dateIn\" /><br><br>\r\n");
      out.write("\t\t\t\t\t<h2>Security Information</h2>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\"> Password: </label><input type=\"password\" name=\"password\" class=\"name1\" Required/> <br><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"\" class = \"label\"> Retype Password: </label><input type=\"password\" name=\"password1\" class=\"name1\" Required /> <br><br>\r\n");
      out.write("\t\t\t    \t<button type=\"submit\" value=\"button8\" name=\"button\">Back</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" value=\"button9\" name=\"button\">Submit</button>\t\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
