/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-18 10:48:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class logIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

String err= "";  
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      Rent.classes.addClass login = null;
      synchronized (session) {
        login = (Rent.classes.addClass) _jspx_page_context.getAttribute("login", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (login == null){
          login = new Rent.classes.addClass();
          _jspx_page_context.setAttribute("login", login, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
 
	String id = request.getParameter("username");
	String password2 = request.getParameter("password2");
	
	if(request.getParameter("button")!=null && request.getParameter("button").equals("button5")){
	
			request.getRequestDispatcher("/boarderProfile.jsp").forward(request, response);
		}
	

	
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Rental System</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/all.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/index.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container_all\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t<p>Contact #: 209-4455 </p>\r\n");
      out.write("\t\t\t<br /><img src=\"img/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<div id=\"buttons\">\r\n");
      out.write("\t\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\"  value=\"button1\" name=\"button\" class=\"active\">HOME</button><br /><hr />\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\"  value=\"button2\" name=\"button\" >VISIT ROOMS</button><hr />\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\"  value=\"button3\" name=\"button\">AVAILABLE ROOMS</button><hr />\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\"  value=\"button4\" name=\"button\" >BOARDERS LIST</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"Controller\" >\r\n");
      out.write("\t\t\t\t<div id=\"login\">\r\n");
      out.write("\t\t\t\t\t<br /><h2>Register/LogIn</h2>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"Enter your ID\" name=\"id\" class=\"id\" required />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" placeholder=\"Password\" name=\"password\" class=\"password\" required />\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t    <button type=\"submit\" value=\"button5\" name=\"button\" style=\"background-color:#ffffff; color:#a7a7a7; border-radius:10px; padding:3px 5px; margin-left:110px;\">logIn</button>\r\n");
      out.write("\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h4>  No account yet? <button type=\"submit\" value=\"button6\" name=\"button\" style=\"border:none; color:red\">Register</button></h4>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" value=\"button7\" name=\"button\" style=\"background-color:#e04a00; padding:12px 15px; border-radius:10px; color:#ffffff;\">logIn as Admin</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<img src=\"img/bhouse.jpg\" alt=\"\" />\t\r\n");
      out.write("\t\t\t<img src=\"img/wanted.png\" alt=\"\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
