/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-04-03 18:42:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_005fcontributions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

String isDisabled = "DISABLED"; String updateValue = "naknang";
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      art.gallery.ArtGallery artgallery = null;
      synchronized (session) {
        artgallery = (art.gallery.ArtGallery) _jspx_page_context.getAttribute("artgallery", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (artgallery == null){
          artgallery = new art.gallery.ArtGallery();
          _jspx_page_context.setAttribute("artgallery", artgallery, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String btn = request.getParameter("btn");
	String[] updateCategories = request.getParameterValues("updatecategory");
	String updateValue2 = updateValue.equals("naknang") ? "Update Categories" : "Confirm Update";
	
	if(btn!=null && btn.startsWith("del ")){
		String entryNumber = btn.substring(4);
		artgallery.deleteArt(entryNumber);
		
	} else if(btn!=null && (btn.equals("naknang") || btn.equals("naknang2"))){
		if(updateValue.equals("naknang")){
			isDisabled = "";
			updateValue = "naknang2";
			updateValue2 = "Confirm Update";
		} else{
			isDisabled = "Disabled";
			updateValue = "naknang";
			updateValue2 = "Update Categories";
			
			artgallery.viewContributions();
			artgallery.confirmUpdate(updateCategories);
			artgallery.clearArtInfo();
		}
	} else if(btn!=null && btn.startsWith("vcm")){
		artgallery.setSelectedEntryId(Integer.parseInt(btn.substring(3, 4)));
		artgallery.setSelectedArtTitle(btn.substring(4));
		request.getRequestDispatcher("/view_comments.jsp").forward(request, response);
	}
	
	artgallery.viewContributions();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Art Gallery System</h1>\r\n");
      out.write("\t\t<h3>Distributions of ");
      out.print(artgallery.getPenName() );
      out.write("</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\t");

				for(int i = 0; i<artgallery.getArtEntryNumber().size(); i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<table border=\"2\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"5\">");
      out.print(artgallery.getArtEntryTitle().get(i) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Art Id</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Category</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Entry Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Gallery Location</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(artgallery.getArtEntryNumber().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"updatecategory\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Painting\" ");
      out.print(artgallery.getArtCategory().get(i).equals("Painting") ? "SELECTED" : "");
      out.write(">Painting</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Craft\" ");
      out.print(artgallery.getArtCategory().get(i).equals("Craft") ? "SELECTED" : "");
      out.write(">Craft</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Sculpture\" ");
      out.print(artgallery.getArtCategory().get(i).equals("Sculpture") ? "SELECTED" : "");
      out.write(">Sculpture</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Photograph\" ");
      out.print(artgallery.getArtCategory().get(i).equals("Photograph") ? "SELECTED" : "");
      out.write(">Photograph</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(artgallery.getArtEntryDate().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(artgallery.getArtLocation().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"del ");
      out.print(artgallery.getArtEntryNumber().get(i) );
      out.write("\" style=\"width: 49%;\">Delete Artwork</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"vcm");
      out.print(artgallery.getArtEntryNumber().get(i) );
      out.print(artgallery.getArtEntryTitle().get(i));
      out.write("\" style=\"width: 49%;\">View Comments</button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");

				} artgallery.clearArtInfo();
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"");
      out.print(updateValue);
      out.write('"');
      out.write('>');
      out.print(updateValue2);
      out.write("</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"backtoauthorpage\">Back</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"logout\">Log Out</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(artgallery.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
artgallery.setMessage("");  
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
