/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-31 17:30:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addnewbook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Library System</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/main.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/adminaddbook.css\" />\r\n");
      out.write("</head>\r\n");
      library.system.LibrarySystem librarySystem = null;
      synchronized (session) {
        librarySystem = (library.system.LibrarySystem) _jspx_page_context.getAttribute("librarySystem", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (librarySystem == null){
          librarySystem = new library.system.LibrarySystem();
          _jspx_page_context.setAttribute("librarySystem", librarySystem, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

	String controlnumber = request.getParameter("controlnumber");
	String booktitle = request.getParameter("booktitle");
	String author= request.getParameter("author");
	String yearpublished = request.getParameter("yearpublished");
	String btn = request.getParameter("btn");
	
	if(btn != null && btn.equals("add")){
		librarySystem.addbook(controlnumber, booktitle, author, yearpublished);
	}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<img src=\"img/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t<h1>Library</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"AdminLoggedIn\">\r\n");
      out.write("\t\t<h1>Logged In as Admin,</h1>\r\n");
      out.write("\t\t<form action=\"Controller\" method=\"get\" id=\"guest1\">\r\n");
      out.write("\t\t<button type=\"submit\" name=\"btn\" value=\"adminlogout\" class=\"logout\"></button><br />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<form action=\"Controller\" method=\"get\" id=\"guest1\">\r\n");
      out.write("\t\t<label for=\"\" class=\"label\">Control Number: </label><input type=\"text\" name=\"controlnumber\" class=\"controlnumber\" /><br />\r\n");
      out.write("\t\t<label for=\"\" class=\"label\">Book Title: </label><input type=\"text\" name=\"booktitle\" class=\"booktitle\" /><br /> \r\n");
      out.write("\t\t<label for=\"\" class=\"label\">Author: </label><input type=\"text\" name=\"author\" class=\"author\" /><br /> \r\n");
      out.write("\t\t<label for=\"\" class=\"label\">Year Published: </label><input type=\"text\" name=\"yearpublished\" class=\"yearpublished\" /><br /> \r\n");
      out.write("\t\t<button type=\"submit\" name=\"btn\" value=\"add\" class=\"add\"></button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<form action=\"Controller\" method=\"get\" id=\"guest1\">\r\n");
      out.write("\t\t<button type=\"submit\" name=\"btn\" value=\"back\" class=\"back\"></button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t");
      out.print(librarySystem.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
librarySystem.setMessage(""); 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
