/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-04-02 08:04:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class new_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Student Insurance System</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/all.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/reset.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/name.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      student.information.system.StudentInfomationSystem sis = null;
      synchronized (session) {
        sis = (student.information.system.StudentInfomationSystem) _jspx_page_context.getAttribute("sis", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sis == null){
          sis = new student.information.system.StudentInfomationSystem();
          _jspx_page_context.setAttribute("sis", sis, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String firstName = request.getParameter("firstName");
	String lastName = request.getParameter("lastName");
	String address = request.getParameter("address");
	String contactNumber = request.getParameter("contactNum");
	String insuranceType = request.getParameter("insuranceType");
	String startingDate = request.getParameter("dateCheckIn");
	String expirationDate = request.getParameter("dateCheckOut");
	
	if(request.getParameter("button")!=null && request.getParameter("button").equals("createSubmit")){		
		sis.setTransactionCommited("Add New Account");
		sis.addNewSIS(firstName, lastName, address, contactNumber, insuranceType, startingDate, expirationDate);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style =background-image:url(img/bg.png);>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<div id=\"form1\">\r\n");
      out.write("\t\t\t<div id=\"title\"><p>STUDENT INSURANCE SYSTEM</p></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tWELCOME, <strong>");
      out.print(sis.getAdminUsername().toUpperCase() );
      out.write("</strong><br>\r\n");
      out.write("\t\t\t<div id=\"title\"><p>ADD INSURANCE</p></div>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h2>Customer Information</h2>\r\n");
      out.write("\t\t\t<form action=\"hrcontroller\" method = \"Post\">\t\r\n");
      out.write("\t\t\t\t<label for=\"\" class = \"label\">First Name: </label><input type=\"text\" name=\"firstName\" class=\"name1\" required /> <br><br>\t\r\n");
      out.write("\t\t\t\t<label for=\"\" class = \"label\">Last Name: </label><input type=\"text\" name=\"lastName\" class=\"name1\" required /> <br><br>\r\n");
      out.write("\t\t\t\t<label for=\"\" class = \"label\">Address: </label><input type=\"text\" name=\"address\" class=\"name1\" required /> <br><br>\r\n");
      out.write("\t\t\t\t<label for=\"\" class = \"label\">Contact No.: </label><input type=\"text\" name=\"contactNum\" class=\"name1\" required /> <br><br>\r\n");
      out.write("\t\t\t<h2>General Information</h2>\r\n");
      out.write("\t\t\t\t<label for=\"\" class = \"label\">Insurance Type: </label>\r\n");
      out.write("\t\t\t\t<select name=\"insuranceType\" class = \"name4\">\r\n");
      out.write("\t\t\t\t\t<option value=\"carinsurance\">Car Insurance</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"healthinsurance\">Health Insurance</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"lifeinsurance\">Life Insurance</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"travelinsurance\">Travel Insurance</option>\r\n");
      out.write("\t\t\t\t</select><br><br>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<label for=\"\" class = \"label\">Starting Date: </label><input type=\"date\" name=\"dateCheckIn\" /><br><br>\r\n");
      out.write("\t\t\t\t<label for=\"\" class = \"label\">Expiration Date: </label><input type=\"date\" name=\"dateCheckOut\" /><br><br>\r\n");
      out.write("\t\t\t\t<button name=\"button\" value = \"createSubmit\">Submit</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form action=\"hrcontroller\" method = \"Post\">\r\n");
      out.write("\t\t\t\t<button name=\"button\" value = \"createBack\">Back</button>\r\n");
      out.write("\t\t\t\t<button name=\"button\" value = \"logout\">Log Out</button>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t");
      out.print(sis.getMessage() );
      out.write("\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t");
if(request.getParameter("button")!=null && request.getParameter("button").equals("createSubmit") && !sis.getMessage().equals("error adding new member, member already exists")){
				out.println("Your New Account Number is: " + sis.getNewAccountNumber(request.getParameter("insuranceType")));
				sis.setTransactionAccountNumber(sis.getNewAccountNumber(request.getParameter("insuranceType")));
				sis.addNewTransaction();
			} 
      out.write("\r\n");
      out.write("\t\t\t");
sis.setMessage(""); 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
