/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-04-02 07:54:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewall_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Student Insurance System</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/all.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/reset.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/name.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      student.information.system.StudentInfomationSystem sis = null;
      synchronized (session) {
        sis = (student.information.system.StudentInfomationSystem) _jspx_page_context.getAttribute("sis", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sis == null){
          sis = new student.information.system.StudentInfomationSystem();
          _jspx_page_context.setAttribute("sis", sis, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	sis.clearCustomers();
	sis.viewAllMembers("", "all");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style =background-image:url(img/bg.png);>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<div id=\"form1\">\r\n");
      out.write("\t\t\t<div id=\"title\"><p>STUDENT INSURANCE SYSTEM</p></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tWELCOME, <strong>");
      out.print(sis.getAdminUsername().toUpperCase() );
      out.write("</strong><br>\r\n");
      out.write("\t\t\t<div id=\"title\"><p>ALL MEMBERS</p></div><br />\t\r\n");
      out.write("\t\t\t<form action=\"hrcontroller\" method = \"Post\">\t\r\n");
      out.write("\t\t\t\t<table border =\"1\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Account #</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Name</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Starting Date</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Expiration Date</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Insurance Type</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

						for(int i = 0; i<sis.getAccountNumber().size(); i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(sis.getAccountNumber().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(sis.getName().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(sis.getStartingDate().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(sis.getExpirationDate().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(sis.getInsuranceType().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t\t<br />\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<button name=\"button\" value = \"viewAllBack\">Back</button>\r\n");
      out.write("\t\t\t\t<button name=\"button\" value = \"logout\">Log Out</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.print(sis.getMessage() );
      out.write("\r\n");
      out.write("\t\t\t");
sis.setMessage(""); 
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
