/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-05-31 10:18:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class laundry_005finformation_005fpage_005fas_005fadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	String updateValue = "Update Status";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Hey Wash Up?!</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/login.css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/registeruser.css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/informationpage.css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/transactionsummary.css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/infopageadmin.css\" /> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      laundry.system.LaundrySystem laundrySystem = null;
      synchronized (session) {
        laundrySystem = (laundry.system.LaundrySystem) _jspx_page_context.getAttribute("laundrySystem", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (laundrySystem == null){
          laundrySystem = new laundry.system.LaundrySystem();
          _jspx_page_context.setAttribute("laundrySystem", laundrySystem, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	
	boolean flagUpdate = false;
	
	String[] status = request.getParameterValues("status");
	
	if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("de ")){
		laundrySystem.removeTransaction(request.getParameter("btn").substring(3));
		updateValue = "Update Status";
		flagUpdate = false;
	} else if(request.getParameter("btn")!=null && (request.getParameter("btn").equals("Update Status") || request.getParameter("btn").equals("Confirm Update"))){
		if(updateValue.equals("Update Status")){
			flagUpdate = true;
			updateValue = "Confirm Update";
		} else{
			laundrySystem.setRecentTransaction("admin");
			laundrySystem.setRecentAdminTransaction();
			laundrySystem.updateStatus(status);
			laundrySystem.clearRecentTransaction();
			updateValue = "Update Status";
		}
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").equals("adminlogout")){
		updateValue = "Update Status";
		flagUpdate = false;
		request.getRequestDispatcher("/laundry_login_page_as_admin.jsp").forward(request, response);
	}
	
	laundrySystem.setRecentTransaction("admin");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<div id=\"main_container\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t<img src=\"img/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div id=\"background\">\r\n");
      out.write("\t<img src=\"img/bg.png\" alt=\"\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<h2>All Transactions</h2>\r\n");
      out.write("\t\t<form action=\"PageController\">\t\t\r\n");
      out.write("\t\t\t<table border=\"2\" cellpadding=\"3\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Transaction Date</th>\r\n");
      out.write("\t\t\t\t\t<th>Email Address</th>\r\n");
      out.write("\t\t\t\t\t<th># of Clothes</th>\r\n");
      out.write("\t\t\t\t\t<th># of Kilo</th>\r\n");
      out.write("\t\t\t\t\t<th>Amount</th>\r\n");
      out.write("\t\t\t\t\t<th>Type of Wash</th>\r\n");
      out.write("\t\t\t\t\t<th>Mode of Payment</th>\r\n");
      out.write("\t\t\t\t\t<th>Type of Service</th>\r\n");
      out.write("\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					for(int i = 0; i<laundrySystem.getRecentTypeOfService().size(); i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentDate().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentEmail().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentTotalNumberOfClothes().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentKilo().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentAmount().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentTypeOfWash().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentModeOfPayment().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(laundrySystem.getRecentTypeOfService().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"status\" value=\"");
      out.print(laundrySystem.getRecentStatus().get(i) );
      out.write('"');
      out.write(' ');
      out.print(flagUpdate==true ? "" : "DISABLED" );
      out.write("/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"de ");
      out.print(laundrySystem.getRecentDate().get(i) );
      out.write("\">Delete Transaction</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					} 	
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"");
      out.print(updateValue );
      out.write('"');
      out.write(' ');
      out.print(laundrySystem.getRecentDate().size()==0 ? "DISABLED" : "" );
      out.write('>');
      out.print(updateValue );
      out.write("</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"adminlogout\">Log Out</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.print(laundrySystem.getMessage() );
      out.write("\r\n");
      out.write("\t\t\t");
laundrySystem.setMessage(""); 
      out.write("\r\n");
      out.write("\t\t\t");
laundrySystem.clearRecentTransaction(); 
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div id=\"footer\"></div>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
