/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-16 10:29:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      thesis.management.ThesisManagement thesisManagement = null;
      synchronized (session) {
        thesisManagement = (thesis.management.ThesisManagement) _jspx_page_context.getAttribute("thesisManagement", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (thesisManagement == null){
          thesisManagement = new thesis.management.ThesisManagement();
          _jspx_page_context.setAttribute("thesisManagement", thesisManagement, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String display = "none";
	String tableDisplay = "none";
	
	String groupNumber = request.getParameter("groupnumber");

	String updateThesisType = request.getParameter("updatethesistype");
	String updateThesisTitle= request.getParameter("updatethesistitle");
	String updateDescription = request.getParameter("updatedescription");
	String[] members = request.getParameterValues("members");
	
	String btn = request.getParameter("btn");
	
	try{
		if(btn.equals("update")){
			thesisManagement.setPanelistVew(groupNumber);
			thesisManagement.setGroupNumber(Integer.parseInt(groupNumber));
			display = "block";
		} else if(btn.equals("passed")){
			thesisManagement.setGuestView(btn);
			tableDisplay = "block";
		} else if(btn.equals("redefense")){
			thesisManagement.setGuestView(btn);
			tableDisplay = "block";		
		} else if(btn.equals("pending")){
			thesisManagement.setGuestView(btn);
			tableDisplay = "block";		
		} else if(btn.equals("passed with modification")){
			thesisManagement.setGuestView(btn);
			tableDisplay = "block";		
		} else if(btn.equals("all")){
			thesisManagement.setGuestView(btn);
			tableDisplay = "block";		
		} else if(btn.equals("confirmupdate")){
			thesisManagement.confirmUpdate(updateThesisType, updateThesisTitle, updateDescription, members);
		} else if(btn.equals("delete")){
			thesisManagement.removeTitle(Integer.parseInt(groupNumber));
		} 
	} catch(Exception e){
		
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Thesis Management System</h1>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\tGroup No.: <input type=\"text\" name=\"groupnumber\" size=\"2\" REQUIRED/><br />\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"update\">Update</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"delete\">Delete</button>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"passed\">View Passed</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"redefense\">View Redefense</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"pending\">View Pending</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"passed with modification\">View Passed with Modification</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"all\">View All</button>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"details\" style=\"display: ");
      out.print(display);
      out.write(";\">\r\n");
      out.write("\t\t\t\t<b>Group Number:</b> <input type=\"text\" value=\"");
      out.print(thesisManagement.getGroupNumber() );
      out.write("\" DISABLED/><br />\r\n");
      out.write("\t\t\t\t<b>Thesis Type:</b> \r\n");
      out.write("\t\t\t\t\t<select name=\"updatethesistype\" id=\"\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Software\" ");
      out.print(thesisManagement.getThesisType().equals("Software") ? "SELECTED" : "" );
      out.write(">Software</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Hardware\" ");
      out.print(thesisManagement.getThesisType().equals("Hardware") ? "SELECTED" : "" );
      out.write(">Hardware</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Software-Hardware\" ");
      out.print(thesisManagement.getThesisType().equals("Software-Hardware") ? "SELECTED" : "" );
      out.write(">Software-Hardware</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<b>Thesis Title:</b> <input type=\"text\" name=\"updatethesistitle\" value=\"");
      out.print(thesisManagement.getThesisTitle() );
      out.write("\" size=\"50\"/><br />\r\n");
      out.write("\t\t\t\t<b>Brief Description:</b> <input type=\"text\" name=\"updatedescription\" value=\"");
      out.print(thesisManagement.getBriefDescription() );
      out.write("\" size=\"50\"/><br /><br />\r\n");
      out.write("\t\t\t\t<b>Members:</b> <br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					for(int i = 0; i<thesisManagement.getMembers().size(); i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"members\" value=\"");
      out.print(thesisManagement.getMembers().get(i) );
      out.write("\"/><br />\r\n");
      out.write("\t\t\t\t");

					} thesisManagement.clearMembers();
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"confirmupdate\">Update Group</button>\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"display: ");
      out.print(tableDisplay);
      out.write(";\">\r\n");
      out.write("\t\t\t\t<table border=\"2\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>Group No</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Thesis Title</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

						for(int i = 0; i<thesisManagement.getGuestGroupNumber().size(); i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(thesisManagement.getGuestGroupNumber().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(thesisManagement.getGuestThesisTitle().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(thesisManagement.getGuestStatus().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						} thesisManagement.clearGuestView();
					
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" value=\"logoutadmin\" name=\"btn\">Log Out</button>\r\n");
      out.write("\t\t</form>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(thesisManagement.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
thesisManagement.setMessage(""); 
      out.write("\t\t\r\n");
      out.write("\t</center>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
