/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-16 10:17:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class asadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      thesis.management.ThesisManagement thesisManagement = null;
      synchronized (session) {
        thesisManagement = (thesis.management.ThesisManagement) _jspx_page_context.getAttribute("thesisManagement", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (thesisManagement == null){
          thesisManagement = new thesis.management.ThesisManagement();
          _jspx_page_context.setAttribute("thesisManagement", thesisManagement, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String username = request.getParameter("ausername");
	String password = request.getParameter("apassword");
	String aSignIn = request.getParameter("asignin");
	
	if(request.getParameter("btn")!=null && request.getParameter("btn").equals("adminsignin")){
		if(thesisManagement.logIn(username, password, "admindb")){
			thesisManagement.setUserName(username);
			request.getRequestDispatcher("/admin.jsp").forward(request, response);
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<h1>Thesis Management System</h1>\r\n");
      out.write("\t<h2>Log In As Administrator</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"PageController\">\r\n");
      out.write("\t\t<label for=\"\">Username</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"ausername\"/>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<label for=\"\">Password</label>\r\n");
      out.write("\t\t<input type=\"password\" name=\"apassword\"/>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<button type=\"submit\" name=\"btn\" value=\"adminsignin\">Sign In</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<button type=\"submit\" name=\"btn\" value=\"backtomainpage\">Back to Main Page</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<br /><br />\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.print(thesisManagement.getMessage() );
      out.write('\r');
      out.write('\n');
      out.write('	');
thesisManagement.setMessage(""); 
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
