/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-16 10:29:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class check_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      thesis.management.ThesisManagement thesisManagement = null;
      synchronized (session) {
        thesisManagement = (thesis.management.ThesisManagement) _jspx_page_context.getAttribute("thesisManagement", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (thesisManagement == null){
          thesisManagement = new thesis.management.ThesisManagement();
          _jspx_page_context.setAttribute("thesisManagement", thesisManagement, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String btn = request.getParameter("btn");
	
	if(btn!=null && btn.equals("gpassed")){
		thesisManagement.setGuestView(btn);
	} else if(btn!=null && btn.equals("gredefense")){
		thesisManagement.setGuestView(btn);
	} else if(btn!=null && btn.equals("gpending")){
		thesisManagement.setGuestView(btn);
	} else if(btn!=null && btn.equals("gpassed with modification")){
		thesisManagement.setGuestView(btn);
	} else if(btn!=null && btn.equals("gall")){
		thesisManagement.setGuestView(btn);
	} 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Thesis Management System</h1>\r\n");
      out.write("\t\t<h2>Check Status</h2>\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"gpassed\">View Passed</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"gredefense\">View Redefense</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"gpending\">View Pending</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"gpassed with modification\">View Passed with Modification</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"gall\">View All</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table border=\"2\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Group No</th>\r\n");
      out.write("\t\t\t\t<th>Thesis Title</th>\r\n");
      out.write("\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				for(int i = 0; i<thesisManagement.getGuestGroupNumber().size(); i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(thesisManagement.getGuestGroupNumber().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(thesisManagement.getGuestThesisTitle().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(thesisManagement.getGuestStatus().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				} thesisManagement.clearGuestView();
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"backtoguest\">Back to Guest Menu</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
