/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-16 10:18:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class panelist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      thesis.management.ThesisManagement thesisManagement = null;
      synchronized (session) {
        thesisManagement = (thesis.management.ThesisManagement) _jspx_page_context.getAttribute("thesisManagement", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (thesisManagement == null){
          thesisManagement = new thesis.management.ThesisManagement();
          _jspx_page_context.setAttribute("thesisManagement", thesisManagement, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String display = "none";

	String groupNumber = request.getParameter("groupnumberp");
	String verdict = request.getParameter("verdict");
	
	if(request.getParameter("btn")!=null && request.getParameter("btn").equals("set")){
		thesisManagement.setPanelistVew(groupNumber);
		display = "block";
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").equals("submitverdict")){
		thesisManagement.updateStatus(verdict);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Thesis Management System</h1>\r\n");
      out.write("\t\t<h2>Log In As Panelist</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\tGroup No.: <input type=\"text\" name=\"groupnumberp\" size=\"5\"/><button type=\"submit\" name=\"btn\" value=\"set\">Set Group</button>\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t\t<div id=\"details\" style=\"display: ");
      out.print(display);
      out.write(";\">\r\n");
      out.write("\t\t\t\t<b>Group Number:</b> ");
      out.print(thesisManagement.getGroupNumber() );
      out.write("<br />\r\n");
      out.write("\t\t\t\t<b>Thesis Type:</b> ");
      out.print(thesisManagement.getThesisType() );
      out.write("<br />\r\n");
      out.write("\t\t\t\t<b>Thesis Title:</b> ");
      out.print(thesisManagement.getThesisTitle() );
      out.write("<br />\r\n");
      out.write("\t\t\t\t<b>Brief Description:</b> ");
      out.print(thesisManagement.getBriefDescription() );
      out.write("<br /><br />\r\n");
      out.write("\t\t\t\t<b>Members:</b> <br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					for(int i = 0; i<thesisManagement.getMembers().size(); i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(thesisManagement.getMembers().get(i) );
      out.write("<br />\r\n");
      out.write("\t\t\t\t");

					} thesisManagement.clearMembers();
				
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"verdict\" value=\"passed\" CHECKED/>\r\n");
      out.write("\t\t\t\t<label for=\"\">Passed</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"verdict\" value=\"passed with modification\" />\r\n");
      out.write("\t\t\t\t<label for=\"\">Passed with Modification</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"verdict\" value=\"pending\" />\r\n");
      out.write("\t\t\t\t<label for=\"\">Pending</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"verdict\" value=\"redefense\" />\r\n");
      out.write("\t\t\t\t<label for=\"\">Redefense</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button type=\"submit\" value=\"submitverdict\" name=\"btn\">SUBMIT</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" value=\"panelistlogout\" name=\"btn\">Log Out</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.print(thesisManagement.getMessage() );
      out.write("\r\n");
      out.write("\t\t\t");
thesisManagement.setMessage(""); 
      out.write("\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
