/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-31 03:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fclass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	String schedule = "";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\" />\r\n");
      out.write("<title>Class Record Project: Add Class</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.ClassRecord classrecord = null;
      synchronized (session) {
        classrecord = (classes.record.ClassRecord) _jspx_page_context.getAttribute("classrecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classrecord == null){
          classrecord = new classes.record.ClassRecord();
          _jspx_page_context.setAttribute("classrecord", classrecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String message = "";

	String addClass = request.getParameter("addclass");
	String back = request.getParameter("back");

	String classYear = request.getParameter("classyear");
	String classSection = request.getParameter("classsection");
	
	String[] days = request.getParameterValues("days");
	String[] fromTime0 = request.getParameterValues("fromtime0");
	String[] fromTime1 = request.getParameterValues("fromtime1");
	String[] from = request.getParameterValues("from");
	String[] toTime0 = request.getParameterValues("totime0");
	String[] toTime1 = request.getParameterValues("totime1");
	String[] to = request.getParameterValues("to");

	if(back!=null){
		classrecord.clearLists();
		classrecord.setMessage("");
		
      if (true) {
        _jspx_page_context.forward("ClassList");
        return;
      }

	} else if(addClass!=null){
		schedule = classrecord.getScheduleOfNewClass(days, fromTime0, fromTime1, from, toTime0, toTime1, to);
		classrecord.addNewClass(classYear, classSection,  schedule);
		classrecord.clearLists();
		
		message = classrecord.getMessage();
		
		if (message.equals("")){
			
      if (true) {
        _jspx_page_context.forward("ClassList");
        return;
      }

		}		
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div class=\"panel panel-info adding\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t<h4>Add New Class</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<form action=\"AddClass\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"classyear\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Class Year...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span> - </span>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<select name=\"classsection\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Section...</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"schedule\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alert alert-info\">Schedule for the Class</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-inline schedules\" id=\"original\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"days\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Monday\">Monday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Tuesday\">Tuesday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Wednesday\">Wednesday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Thursday\">Thursday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Friday\">Friday</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Saturday\">Saturday</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"from\">From:</span> <select name=\"fromtime0\" id=\"\" class=\"btn btn-default\" id=\"from\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> : </span>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"fromtime1\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00\">00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17\">17</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18\">18</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21\">21</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23\">23</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"24\">24</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"25\">25</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"26\">26</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"27\">27</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"28\">28</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"29\">29</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"31\">31</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"32\">32</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"33\">33</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"34\">34</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"35\">35</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"36\">36</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"37\">37</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"38\">38</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"39\">39</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"40\">40</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"41\">41</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"42\">42</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"43\">43</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"44\">44</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"45\">45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"46\">46</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"47\">47</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"48\">48</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"49\">49</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"50\">50</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"51\">51</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"52\">52</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"53\">53</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"54\">54</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"55\">55</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"56\">56</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"57\">57</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"58\">58</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"59\">59</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"60\">60</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"from\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"AM\">AM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"AM\">PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"to\">To:</span> <select name=\"totime0\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> : </span>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"totime1\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"00\">00</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"17\">17</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"18\">18</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"21\">21</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"23\">23</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"24\">24</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"25\">25</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"26\">26</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"27\">27</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"28\">28</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"29\">29</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"31\">31</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"32\">32</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"33\">33</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"34\">34</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"35\">35</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"36\">36</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"37\">37</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"38\">38</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"39\">39</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"40\">40</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"41\">41</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"42\">42</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"43\">43</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"44\">44</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"45\">45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"46\">46</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"47\">47</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"48\">48</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"49\">49</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"50\">50</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"51\">51</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"52\">52</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"53\">53</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"54\">54</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"55\">55</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"56\">56</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"57\">57</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"58\">58</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"59\">59</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"60\">60</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"to\" id=\"\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"AM\">AM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"AM\">PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"Add Time\" class=\"btn btn-warning btn-sm buton\" id=\"addschedule\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"Remove Time\" class=\"btn btn-danger btn-sm buton\" id=\"removeschedule\"/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"addclass\" value=\"Add Class\" class=\"btn btn-primary buton\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"back\" value=\"Back to Class List\" class=\"btn btn-info buton\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(!message.equals("")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-danger\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(message );
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t");

						classrecord.setMessage("");
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar divCount = 1; \r\n");
      out.write("\t\tvar scheduleDiv = document.getElementById(\"schedule\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"addschedule\").onclick = function(){\r\n");
      out.write("\t\t\tvar original = document.getElementById(\"original\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar clone = original.cloneNode(true);\r\n");
      out.write("\t\t\tclone.id = \"duplicate\" + divCount;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar hr = document.createElement(\"hr\");\r\n");
      out.write("\t\t\thr.id = \"hr\" + divCount;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tscheduleDiv.appendChild(hr);\r\n");
      out.write("\t\t\tscheduleDiv.appendChild(clone);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdivCount++;\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"removeschedule\").onclick = function(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"duplicate\" + (divCount - 1)).remove();\r\n");
      out.write("\t\t\tdocument.getElementById(\"hr\" + (divCount - 1)).remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdivCount--;\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
