/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-31 03:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fstudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\" />\r\n");
      out.write("<title>Class Record Project: Add New Student</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.ClassRecord classrecord = null;
      synchronized (session) {
        classrecord = (classes.record.ClassRecord) _jspx_page_context.getAttribute("classrecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classrecord == null){
          classrecord = new classes.record.ClassRecord();
          _jspx_page_context.setAttribute("classrecord", classrecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String message = "";

	String studentId = request.getParameter("studentid");
	String lastName = request.getParameter("lastname");
	String firstName = request.getParameter("firstname");
	String middleName = request.getParameter("middlename");
	String address = request.getParameter("address");
	String contact = request.getParameter("contact");
	String gender = request.getParameter("gender");
	
	String addNewStudent = request.getParameter("addstudent");
	String backToClassList = request.getParameter("backtoclasslist");
	
	if(addNewStudent!=null){
		classrecord.setFullName(lastName, firstName, middleName, studentId, address, contact);
		
		message = classrecord.getMessage();
		
		if (message.equals("")){
			classrecord.addNewStudent(studentId, classrecord.getFullName(), address, contact, gender);
			classrecord.clearLists();
			
			message = classrecord.getMessage();
		
			
      if (true) {
        _jspx_page_context.forward("StudentList");
        return;
      }

		}
	} else if(backToClassList!=null){
		classrecord.clearLists();
		
      if (true) {
        _jspx_page_context.forward("StudentList");
        return;
      }

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div class=\"panel panel-info adding\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t<h4>Add New Student</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<form action=\"AddNewStudent\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"studentid\" placeholder=\"Student ID\" class=\"form-control\"/><br />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"lastname\" placeholder=\"Last Name\" class=\"form-control\" id=\"lastname\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"firstname\" placeholder=\"First Name\" class=\"form-control\" id=\"firstname\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"middlename\" placeholder=\"Middle Name\" class=\"form-control\" id=\"middlename\"/><br />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"address\" placeholder=\"Address\" class=\"form-control\"/><br />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"contact\" placeholder=\"Contact Details\" class=\"form-control\"/><br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"Male\" id=\"male\" CHECKED/> Male\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"Female\"/> Female\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br /><hr />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"addstudent\" value=\"Add New Student\" class=\"btn btn-primary\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"backtoclasslist\" value=\"Back to Class List\" class=\"btn btn-info\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(!message.equals("")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-danger\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(message );
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t");

						classrecord.setMessage("");
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
