/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-31 03:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class grade_005fsheet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	boolean DISABLED = true;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\" />\r\n");
      out.write("<title>Class Record Project: Grade Sheet Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.ClassRecord classrecord = null;
      synchronized (session) {
        classrecord = (classes.record.ClassRecord) _jspx_page_context.getAttribute("classrecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classrecord == null){
          classrecord = new classes.record.ClassRecord();
          _jspx_page_context.setAttribute("classrecord", classrecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String updateGrades = request.getParameter("updategradesheet");
	String back = request.getParameter("backtostudentlist");
	String setForm = request.getParameter("setform");

	String quiz1 = request.getParameter("quiz1");
	String quiz2 = request.getParameter("quiz2");
	String midtermExam = request.getParameter("midtermexam");
	String midtermProject = request.getParameter("midtermproject");
	String quiz3 = request.getParameter("quiz3");
	String quiz4 = request.getParameter("quiz4");
	String finalExam = request.getParameter("finalexam");
	String finalProject = request.getParameter("finalproject");
	
	if(back!=null){
		classrecord.clearLists();
		
      if (true) {
        _jspx_page_context.forward("StudentList");
        return;
      }

	} else if(setForm!=null){
		DISABLED = false;
	} else if(updateGrades!=null){
		classrecord.updateGradeSheet(quiz1, quiz2, midtermExam, midtermProject, quiz3, quiz4, finalExam, finalProject);
		DISABLED = true;
	}
	
	classrecord.setGrades();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div class=\"panel panel-info tabled\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t<h4>");
      out.print(classrecord.getStudent() );
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print(classrecord.getNameOfStudent() );
      out.write("</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<form action=\"GradeSheet\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"4\">Midterms</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Quiz no. 1</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Quiz no. 2</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Mid Exam</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Mid Project</th>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"quiz1\" value=\"");
      out.print(classrecord.getQuiz1() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"quiz2\" value=\"");
      out.print(classrecord.getQuiz2() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"midtermexam\" value=\"");
      out.print(classrecord.getMidtermExam() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"midtermproject\" value=\"");
      out.print(classrecord.getMidtermProject() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"4\">Finals</th>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Quiz no. 3</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Quiz no. 4</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Final Exam</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Final Project</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"quiz3\" value=\"");
      out.print(classrecord.getQuiz3() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"quiz4\" value=\"");
      out.print(classrecord.getQuiz4() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"finalexam\" value=\"");
      out.print(classrecord.getFinalExam() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"finalproject\" value=\"");
      out.print(classrecord.getFinalProject() );
      out.write('"');
      out.write(' ');
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"form-control\"/></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"setform\" value=\"Set Forms\" ");
      out.print(DISABLED==false ? "DISABLED" : "" );
      out.write(" class=\"btn btn-warning buton\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"updategradesheet\" value=\"Update Grade Sheet\" ");
      out.print(DISABLED==true ? "DISABLED" : "" );
      out.write(" class=\"btn btn-success buton\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"backtostudentlist\"  value=\"Back to Student List\" class=\"btn btn-info buton\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
classrecord.clearLists();
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
