/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-18 17:48:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fnew_005fplan_005ftype_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      funeral.plan.FuneralPlan funeralPlan = null;
      synchronized (session) {
        funeralPlan = (funeral.plan.FuneralPlan) _jspx_page_context.getAttribute("funeralPlan", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (funeralPlan == null){
          funeralPlan = new funeral.plan.FuneralPlan();
          _jspx_page_context.setAttribute("funeralPlan", funeralPlan, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String planType = request.getParameter("plantype");
	String description = request.getParameter("description");
	String contractPrice = request.getParameter("contractprice");
	String annual = request.getParameter("annualprice");
	String semiAnnual = request.getParameter("semiannualprice");
	String quarterly = request.getParameter("quarterlyprice");
	String monthly = request.getParameter("monthlyprice");
	
	if(request.getParameter("btn")!=null && request.getParameter("btn").equals("addplantype")){
		funeralPlan.addNewPlanType(planType, description, contractPrice, annual, semiAnnual, quarterly, monthly);
		request.getRequestDispatcher("/selected_plan_type_table.jsp").forward(request, response);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\tPlan Type: <input type=\"text\" name=\"plantype\"/><br /><br />\r\n");
      out.write("\t\t\tDescription: <textarea name=\"description\" cols=\"30\" rows=\"10\"></textarea><br /><br />\r\n");
      out.write("\t\t\tContract Price: <input type=\"text\" name=\"contractprice\" /><br /><br />\r\n");
      out.write("\t\t\tAnnual: <input type=\"text\" name=\"annualprice\"/><br /><br />\r\n");
      out.write("\t\t\tSemiAnnual: <input type=\"text\" name=\"semiannualprice\"/><br /><br />\r\n");
      out.write("\t\t\tQuarterly: <input type=\"text\" name=\"quarterlyprice\"/><br /><br />\r\n");
      out.write("\t\t\tMonthly: <input type=\"text\" name=\"monthlyprice\"/><br /><br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"addplantype\">Add</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"canceladd\">Cancel</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
