/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-24 07:42:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class selected_005fplan_005ftype_005ftable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      funeral.plan.FuneralPlan funeralPlan = null;
      synchronized (session) {
        funeralPlan = (funeral.plan.FuneralPlan) _jspx_page_context.getAttribute("funeralPlan", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (funeralPlan == null){
          funeralPlan = new funeral.plan.FuneralPlan();
          _jspx_page_context.setAttribute("funeralPlan", funeralPlan, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String selectedPlanType = request.getParameter("selectedplantype");
	String selectedPaymentType = request.getParameter("selectedpaymenttype");
	
	if(request.getParameter("btn")!=null && request.getParameter("btn").equals("submit")){
		funeralPlan.submitSelectedPlan(selectedPlanType, selectedPaymentType);
		funeralPlan.addToTransactionLog();
		request.getRequestDispatcher("/submitted_data.jsp").forward(request, response);
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("udtpln ")){
		funeralPlan.setPlanType(request.getParameter("btn").substring(7));
		request.getRequestDispatcher("/update_plan_type.jsp").forward(request, response);
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("rmvpln ")){
		funeralPlan.removePlanType(request.getParameter("btn").substring(7));
	}
	
	funeralPlan.clearPlanTable();
	funeralPlan.setSelectedPlan();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>");
      out.print(funeralPlan.getSelectedPlanType() );
      out.write("</h1>\r\n");
      out.write("\t\t<table border=\"2\" cellpadding=\"10\" style=\"width: 1000px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"8\">Hello, <strong>");
      out.print(funeralPlan.getName() );
      out.write("</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Plan Type</th>\r\n");
      out.write("\t\t\t\t<th>Description </th>\r\n");
      out.write("\t\t\t\t<th>Contract Price</th>\r\n");
      out.write("\t\t\t\t<th>Annual</th>\r\n");
      out.write("\t\t\t\t<th>SemiAnnually</th>\r\n");
      out.write("\t\t\t\t<th>Quarterly</th>\r\n");
      out.write("\t\t\t\t<th>Monthly</th>\r\n");
      out.write("\t\t\t\t");
if(funeralPlan.getName().equals("admin")){
      out.write("<th></th>");
}
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				for(int i = 0; i<funeralPlan.getPlanTypes().size(); i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(funeralPlan.getPlanTypes().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(funeralPlan.getDescriptions().get(i).replace(", ", "<br />") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(funeralPlan.getContractPrices().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(funeralPlan.getAnnuals().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(funeralPlan.getSemiAnnuals().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(funeralPlan.getQuarterlys().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(funeralPlan.getMonthlys().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td><form action=\"PageController\">");
if(funeralPlan.getName().equals("admin")){
      out.write(" <button type=\"submit\" name=\"btn\" value=\"udtpln ");
      out.print(funeralPlan.getPlanTypes().get(i) );
      out.write("\">Update Plan</button><br /><button type=\"submit\" name=\"btn\" value=\"rmvpln ");
      out.print(funeralPlan.getPlanTypes().get(i) );
      out.write("\">Delete Plan</button>");
}
      out.write("</form></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				} 
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\t");

				if(!funeralPlan.getName().equals("admin")){
			
      out.write("\r\n");
      out.write("\t\t\t\t<select name=\"selectedplantype\" id=\"\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">Type of Plan...</option>\r\n");
      out.write("\t\t\t\t\t");

						for(int i = 0; i<funeralPlan.getPlanTypes().size(); i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(funeralPlan.getPlanTypes().get(i) );
      out.write('"');
      out.write('>');
      out.print(funeralPlan.getPlanTypes().get(i) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<select name=\"selectedpaymenttype\" id=\"\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">Type of Payment...</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"contract_price\">Full Payment</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"annual\">Annual</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"semi_annual\">Semi Annual</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"quarterly\">Quarterly</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"monthly\">Monthly</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"submit\">Submit</button><br />\r\n");
      out.write("\t\t\t");

				} else if(funeralPlan.getName().equals("admin")){
			
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"addnewplantype\">Add New Plan Type</button><br />\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"back\">Back to Plan List</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
