/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-24 07:42:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class update_005fplan_005ftype_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      funeral.plan.FuneralPlan funeralPlan = null;
      synchronized (session) {
        funeralPlan = (funeral.plan.FuneralPlan) _jspx_page_context.getAttribute("funeralPlan", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (funeralPlan == null){
          funeralPlan = new funeral.plan.FuneralPlan();
          _jspx_page_context.setAttribute("funeralPlan", funeralPlan, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String updatedPlanType = request.getParameter("updateplantype");
	String updatedDescription = request.getParameter("updatedescription");
	String updatedContractPrice = request.getParameter("updatecontractprice");
	String updatedAnnual = request.getParameter("annualprice");
	String updatedSemiAnnual = request.getParameter("semiannualprice");
	String updatedQuarterly = request.getParameter("quarterlyprice");
	String updatedMonthly = request.getParameter("monthlyprice");

	if(request.getParameter("btn")!=null && request.getParameter("btn").equals("updateplantype")){
		funeralPlan.updatePlanTypes(updatedPlanType, updatedDescription, updatedContractPrice, updatedAnnual, updatedSemiAnnual, updatedQuarterly, updatedMonthly);
		request.getRequestDispatcher("/selected_plan_type_table.jsp").forward(request, response);
	}
	
	funeralPlan.setUpdateFields();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"PageController\">\r\n");
      out.write("\t\t\tPlan Type: <input type=\"text\" name=\"updateplantype\" value=\"");
      out.print(funeralPlan.getPlanTypes().get(0));
      out.write("\"/><br /><br />\r\n");
      out.write("\t\t\tDescription: <textarea name=\"updatedescription\" cols=\"30\" rows=\"10\">");
      out.print(funeralPlan.getDescriptions().get(0));
      out.write("</textarea><br /><br />\r\n");
      out.write("\t\t\tContract Price: <input type=\"text\" name=\"updatecontractprice\" value=\"");
      out.print(funeralPlan.getContractPrices().get(0));
      out.write("\"/><br /><br />\r\n");
      out.write("\t\t\tAnnual: <input type=\"text\" name=\"annualprice\" value=\"");
      out.print(funeralPlan.getAnnuals().get(0));
      out.write("\"/><br /><br />\r\n");
      out.write("\t\t\tSemiAnnual: <input type=\"text\" name=\"semiannualprice\" value=\"");
      out.print(funeralPlan.getSemiAnnuals().get(0));
      out.write("\"/><br /><br />\r\n");
      out.write("\t\t\tQuarterly: <input type=\"text\" name=\"quarterlyprice\" value=\"");
      out.print(funeralPlan.getQuarterlys().get(0));
      out.write("\"/><br /><br />\r\n");
      out.write("\t\t\tMonthly: <input type=\"text\" name=\"monthlyprice\" value=\"");
      out.print(funeralPlan.getMonthlys().get(0));
      out.write("\"/><br /><br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"updateplantype\">Update</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"cancelupdate\">Cancel</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
funeralPlan.clearPlanTable(); 
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
