/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-19 19:23:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class class_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\" />\r\n");
      out.write("<title>Class Record Project: Classes Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.NewClassRecord classRecord = null;
      synchronized (session) {
        classRecord = (classes.record.NewClassRecord) _jspx_page_context.getAttribute("classRecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classRecord == null){
          classRecord = new classes.record.NewClassRecord();
          _jspx_page_context.setAttribute("classRecord", classRecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String message = "";
	String btn = request.getParameter("btn");
	
	String[] classes = request.getParameterValues("classes");
	
	if(btn!=null && btn.startsWith("std ")){
		classRecord.setClassInfo(btn.substring(4));
		request.getRequestDispatcher("/StudentList").forward(request, response);		
	} else if(btn!=null && btn.equals("deleteclass")){
		classRecord.delete(classes, "classes");
	}

	message = classRecord.getMessage();
	classRecord.clearClassLists();
	classRecord.setList("classes");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div class=\"panel panel-primary tabled\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t<h4>Class List</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<form action=\"MainPageController\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"checkAllClasses\" ");
      out.print(classRecord.getRow("classes")<1 ? "DISABLED" : "" );
      out.write("/></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>List of Students</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Number of Students</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Class Schedule</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							for(int i = 0;i<classRecord.getClassYearSection().size(); i++){
								String classSchedule = classRecord.getClassSchedule().get(i).replace("/", "<br />");
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"active\"><input type=\"checkbox\" name=\"classes\" value=\"");
      out.print(classRecord.getClassYearSection().get(i) );
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(classRecord.getClassYearSection().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(classRecord.getNumberOfStudents().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(classSchedule );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"std ");
      out.print(classRecord.getClassYearSection().get(i) );
      out.write("\" class=\"btn btn-success btn-sm buton-class\">View Students</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
	
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"addnewclass\" class=\"btn btn-primary buton\">Add New Class</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"deleteclass\" class=\"btn btn-danger buton\" id=\"btndel\" ");
      out.print(classRecord.getRow("classes")==0 ? "DISABLED" : "" );
      out.write(">Delete Class</button>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(!message.equals("")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-danger\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(message );
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t");

						classRecord.setMessage("");
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload = function(){\r\n");
      out.write("\t\t\tcheckAll();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction checkAll(){\r\n");
      out.write("\t\t\tvar classes = document.getElementsByName(\"classes\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"checkAllClasses\").onclick = function(){\t\t\t\t\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"checkAllClasses\").checked){\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i< classes.length; i++){\r\n");
      out.write("\t\t\t\t\t\tclasses[i].checked  = true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else{\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i< classes.length; i++){\r\n");
      out.write("\t\t\t\t\t\tclasses[i].checked  = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
