/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-30 15:44:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fstudent_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Add Student</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.ClassRecordManager classRecord = null;
      synchronized (session) {
        classRecord = (classes.record.ClassRecordManager) _jspx_page_context.getAttribute("classRecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classRecord == null){
          classRecord = new classes.record.ClassRecordManager();
          _jspx_page_context.setAttribute("classRecord", classRecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	if(session.getAttribute("id")==null || classRecord.getLoggedId().equals("")){
		session.invalidate();
		request.getRequestDispatcher("/login_page.jsp").forward(request, response);
	}

	String btn = request.getParameter("btn");

	String studentId = request.getParameter("studentid");
	String lastName = request.getParameter("lastname");
	String firstName = request.getParameter("firstname");
	String middleName = request.getParameter("middlename");
	String studentYear = request.getParameter("studentyear");
	String studentSection = request.getParameter("studentsection");
	
	if(btn!=null && btn.equals("addstudent")){
		String[] fieldValues = {studentId, firstName + " " + middleName + " " + lastName, studentYear + "-" + studentSection};
		classRecord.add("student", fieldValues);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Class Record</h1>\r\n");
      out.write("\t\t<h3>Add New Student</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"ClassController\" method=\"post\">\r\n");
      out.write("\t\t\tStudent ID: <input type=\"text\" name=\"studentid\"/><br /><br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tLast Name: <input type=\"text\" name=\"lastname\"/><br /><br />\r\n");
      out.write("\t\t\tFirst Name: <input type=\"text\" name=\"firstname\"/><br /><br />\r\n");
      out.write("\t\t\tMiddle Name: <input type=\"text\" name=\"middlename\"/><br /><br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<select name=\"studentyear\" id=\"\">\r\n");
      out.write("\t\t\t\t<option value=\"\">Student Year...</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<span> - </span>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<select name=\"studentsection\" id=\"\">\r\n");
      out.write("\t\t\t\t<option value=\"\">Student Section...</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"addstudent\">Add Student</button>\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"ClassController\" method=\"post\">\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"backtostudentlist\">Back</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(classRecord.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
classRecord.setMessage(""); 
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
