/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-30 13:53:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faculty_005fregistration_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sign Up</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.ClassRecordManager classRecord = null;
      synchronized (session) {
        classRecord = (classes.record.ClassRecordManager) _jspx_page_context.getAttribute("classRecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classRecord == null){
          classRecord = new classes.record.ClassRecordManager();
          _jspx_page_context.setAttribute("classRecord", classRecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String btn = request.getParameter("btn");
	
	String lastName = request.getParameter("facultylastname");
	String firstName = request.getParameter("facultyfirstname");
	String middleName = request.getParameter("facultymiddlename");
	String password = request.getParameter("facultypassword");
	String retypePassword = request.getParameter("facultyretypepassword");

	String[] fieldValues = {lastName, firstName, middleName, password, retypePassword};
	
	if(btn!=null && btn.equals("register")){
		classRecord.add("faculty", fieldValues);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Class Record</h1>\r\n");
      out.write("\t\t<h3>Faculty Registration</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"ClassController\" method=\"post\">\r\n");
      out.write("\t\t\tLast Name: <input type=\"text\" name=\"facultylastname\" REQUIRED/><br />\r\n");
      out.write("\t\t\tFirst Name: <input type=\"text\" name=\"facultyfirstname\" REQUIRED/><br />\r\n");
      out.write("\t\t\tMiddle Name: <input type=\"text\" name=\"facultymiddlename\"/><br />\r\n");
      out.write("\t\t\tPassword: <input type=\"password\" name=\"facultypassword\" REQUIRED/><br />\r\n");
      out.write("\t\t\tRetype Password: <input type=\"password\" name=\"facultyretypepassword\" REQUIRED/><br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"register\">Submit!</button>\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"ClassController\" method=\"post\">\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"backtologin\">Back To Login Page</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(classRecord.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
classRecord.setMessage(""); 
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
