/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-30 15:44:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class grade_005fsheet_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	String[] grades = {"", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0"};

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Grade Sheet</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.ClassRecordManager classRecord = null;
      synchronized (session) {
        classRecord = (classes.record.ClassRecordManager) _jspx_page_context.getAttribute("classRecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classRecord == null){
          classRecord = new classes.record.ClassRecordManager();
          _jspx_page_context.setAttribute("classRecord", classRecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String updateValue = "Update Grade(s)";
	String isDisabled = "DISABLED";

	String btn = request.getParameter("btn");
	String[] grade = request.getParameterValues("grades");

	if(session.getAttribute("id")==null || classRecord.getLoggedId().equals("")){
		request.getRequestDispatcher("/login_page.jsp").forward(request, response);
	}

	if(btn!=null && btn.equals("gradelogout")){
		session.invalidate();
		request.getRequestDispatcher("/login_page.jsp").forward(request, response);
	} else if(btn!=null && (btn.equals("Update Grade(s)") || btn.equals("Confirm Update"))){
		if(btn.equals("Update Grade(s)")){
			isDisabled = "";
			updateValue = "Confirm Update";
		} else {
			classRecord.update(grade);
			isDisabled = "DISABLED";
			updateValue = "Update Grade(s)";
		}
	}
	
	classRecord.setTable("grade");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Class Record</h1>\r\n");
      out.write("\t\t<h2>Grade Sheet</h2>\r\n");
      out.write("\t\t<h3>Student Information</h3>\r\n");
      out.write("\t\t<h4>");
      out.print(classRecord.getGradeSelectedStudentId() );
      out.write("</h4>\r\n");
      out.write("\t\t<h4>");
      out.print(classRecord.getGradeSelectedStudentName() );
      out.write("</h4>\r\n");
      out.write("\t\t<form action=\"ClassController\" method=\"post\">\r\n");
      out.write("\t\t\t<table border=\"1\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"4\">Mid-Term Period</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Q1</th>\r\n");
      out.write("\t\t\t\t\t<th>Q2</th>\r\n");
      out.write("\t\t\t\t\t<th>MTE</th>\r\n");
      out.write("\t\t\t\t\t<th>MTP</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeMidtermQuiz1().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeMidtermQuiz2().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeMidtermExam().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeMidtermProject().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table border=\"1\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"4\">Final Period</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Q3</th>\r\n");
      out.write("\t\t\t\t\t<th>Q4</th>\r\n");
      out.write("\t\t\t\t\t<th>FE</th>\r\n");
      out.write("\t\t\t\t\t<th>FP</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeFinalQuiz3().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeFinalQuiz4().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeFinalExam().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"grades\" id=\"\" ");
      out.print(isDisabled );
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int i = 0; i<grades.length; i++){
      out.write(" <option value=\"");
      out.print(grades[i]);
      out.write('"');
      out.write(' ');
      out.print(classRecord.getGradeFinalProject().equals(grades[i]) ? "SELECTED" : "" );
      out.write('>');
      out.print(grades[i]);
      out.write("</option>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"");
      out.print(updateValue );
      out.write('"');
      out.write('>');
      out.print(updateValue );
      out.write("</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"backtostudentlist\">Back</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"gradelogout\">Log Out</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(classRecord.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
classRecord.setMessage(""); 
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
