/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-03-30 15:44:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_005flist_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Students List</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      classes.record.ClassRecordManager classRecord = null;
      synchronized (session) {
        classRecord = (classes.record.ClassRecordManager) _jspx_page_context.getAttribute("classRecord", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (classRecord == null){
          classRecord = new classes.record.ClassRecordManager();
          _jspx_page_context.setAttribute("classRecord", classRecord, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	if(session.getAttribute("id")==null || classRecord.getLoggedId().equals("")){
		session.invalidate();
		request.getRequestDispatcher("/login_page.jsp").forward(request, response);
	}

	String btn = request.getParameter("btn");

	if(btn!=null && btn.equals("studentlogout")){
		session.invalidate();
		request.getRequestDispatcher("/login_page.jsp").forward(request, response);
	} else if(btn!=null && btn.startsWith("dls")){
		classRecord.delete("student", btn.substring(4));
	} else if(btn!=null && btn.startsWith("grd")){
		String[] students = btn.split("/");
		String selectedSubjectCode = students[0].substring(4);
		String selectedStudentId = students[1];
		String selectedStudentName = students[2];
		
		classRecord.setGradeSelectedSubjectCode(selectedSubjectCode);
		classRecord.setGradeSelectedStudentId(selectedStudentId);
		classRecord.setGradeSelectedStudentName(selectedStudentName);
		request.getRequestDispatcher("/grade_sheet_page.jsp").forward(request, response);
	}
	
	classRecord.clearStudentInfo();
	classRecord.setTable("student");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Class Record</h1>\r\n");
      out.write("\t\t<h2>Student List</h2>\r\n");
      out.write("\t\t<h3>Faculty: ");
      out.print(classRecord.getLoggedName() );
      out.write("</h3>\r\n");
      out.write("\t\t<form action=\"ClassController\" method=\"post\">\r\n");
      out.write("\t\t\t<table border=\"1\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Subject Code</th>\r\n");
      out.write("\t\t\t\t\t<th>Student Id</th>\r\n");
      out.write("\t\t\t\t\t<th>Student Name</th>\r\n");
      out.write("\t\t\t\t\t<th>Year And Section</th>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\">Actions</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					for(int i = 0; i<classRecord.getStudentEntryNumber().size(); i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(classRecord.getStudentSubjectCode().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(classRecord.getStudentId().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(classRecord.getStudentName().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(classRecord.getStudentYearAndSection().get(i) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"grd ");
      out.print(classRecord.getStudentSubjectCode().get(i) );
      out.write('/');
      out.print(classRecord.getStudentId().get(i) );
      out.write('/');
      out.print(classRecord.getStudentName().get(i) );
      out.write("\">View Grades</button></td>\r\n");
      out.write("\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"dls ");
      out.print(classRecord.getStudentEntryNumber().get(i) );
      out.write("\">Delete</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
	
					}				
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"backtoclasslist\">Back</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"addnewstudent\">Add New Student</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"studentlogout\">Log Out</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.print(classRecord.getMessage() );
      out.write("\r\n");
      out.write("\t\t");
classRecord.setMessage(""); 
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
