/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-04-02 14:35:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fnew_005fhotel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Add New Hotel</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      hotel.reservation.HotelReservation hotelReservation = null;
      synchronized (session) {
        hotelReservation = (hotel.reservation.HotelReservation) _jspx_page_context.getAttribute("hotelReservation", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (hotelReservation == null){
          hotelReservation = new hotel.reservation.HotelReservation();
          _jspx_page_context.setAttribute("hotelReservation", hotelReservation, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

	String hotelCityMunicipality = request.getParameter("newhotelcitymunicipality");

	String hotelName = request.getParameter("newhotelname");
	String routeFrom = request.getParameter("newroutefrom");
	String description = request.getParameter("newdescription");

	String hotelAddress = request.getParameter("newhoteladdress");
	String hotelContact = request.getParameter("newhotelcontact");
	
	if(request.getParameter("btn")!=null && request.getParameter("btn").equals("add")){
		hotelReservation.setCityMunicipality(hotelCityMunicipality);
		hotelReservation.addNewHotel(hotelName, routeFrom, description, hotelAddress, hotelContact);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\t<h1>Hotel Accommodation System</h1>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"accommodation\">Accommodation</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"sightsandactivities\">Sights and Activities</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"planyourvisit\">Plan Your Visit</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"contactus\">Contact Us</button>\r\n");
      out.write("\t\t\t");

				if(hotelReservation.getLoggedIn().equals("")){
			
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"adminback\">Back</button>\r\n");
      out.write("\t\t\t");

				} else{
			
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"addnewhotel\">Add New Hotel</button>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"logout\">Log Out</button>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\tChoose City/ Municipality: \r\n");
      out.write("\t\t\t<select name=\"newhotelcitymunicipality\" id=\"\" REQUIRED>\r\n");
      out.write("\t\t\t\t<option value=\"\">City/Municipality...</option>\r\n");
      out.write("\t\t\t\t<option value=\"Caloocan\">Caloocan</option>\r\n");
      out.write("\t\t\t\t<option value=\"Las Piñas\">Las Piñas</option>\r\n");
      out.write("\t\t\t\t<option value=\"Makati\">Makati</option>\r\n");
      out.write("\t\t\t\t<option value=\"Malabon\">Malabon</option>\r\n");
      out.write("\t\t\t\t<option value=\"Mandaluyong\">Mandaluyong</option>\r\n");
      out.write("\t\t\t\t<option value=\"Manila\">Manila</option>\r\n");
      out.write("\t\t\t\t<option value=\"Marikina\">Marikina</option>\r\n");
      out.write("\t\t\t\t<option value=\"Muntinlupa\">Muntinlupa</option>\r\n");
      out.write("\t\t\t\t<option value=\"Navotas\">Navotas</option>\r\n");
      out.write("\t\t\t\t<option value=\"Parañaque\">Parañaque</option>\r\n");
      out.write("\t\t\t\t<option value=\"Pasay\">Pasay</option>\r\n");
      out.write("\t\t\t\t<option value=\"Pasig\">Pasig</option>\r\n");
      out.write("\t\t\t\t<option value=\"Pateros\">Pateros</option>\r\n");
      out.write("\t\t\t\t<option value=\"Quezon City\">Quezon City</option>\r\n");
      out.write("\t\t\t\t<option value=\"San Juan\">San Juan</option>\r\n");
      out.write("\t\t\t\t<option value=\"Taguig\">Taguig</option>\r\n");
      out.write("\t\t\t\t<option value=\"Valenzuela\">Valenzuela</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tHotel Name: <input type=\"text\" name=\"newhotelname\" REQUIRED/><br />\r\n");
      out.write("\t\t\tRoute From: <input type=\"text\" name=\"newroutefrom\" REQUIRED/><br />\r\n");
      out.write("\t\t\tDescription: <input type=\"text\" name=\"newdescription\" REQUIRED/><br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tHotel Address: <input type=\"text\" name=\"newhoteladdress\" REQUIRED/><br />\r\n");
      out.write("\t\t\tHotel Contact: <input type=\"text\" name=\"newhotelcontact\" REQUIRED/><br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"add\">Add New Hotel</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"cancel\">Cancel</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
