/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-04-04 06:05:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;

public final class hotels_005flists_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	String checkBoxValue = "";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Hotels Lists</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      hotel.reservation.HotelReservation hotelReservation = null;
      synchronized (session) {
        hotelReservation = (hotel.reservation.HotelReservation) _jspx_page_context.getAttribute("hotelReservation", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (hotelReservation == null){
          hotelReservation = new hotel.reservation.HotelReservation();
          _jspx_page_context.setAttribute("hotelReservation", hotelReservation, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	
	String[] checks = request.getParameterValues("check");
	String headerVal = hotelReservation.getLoggedIn().equals("") ? "Information" : "Action";
	
	if(request.getParameter("btn")!=null && request.getParameter("btn").equals("remove")){
		hotelReservation.removeHotel(checks);
		checkBoxValue = "";
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("vhl")){
		hotelReservation.setEntryId(request.getParameter("btn").substring(4));
		request.getRequestDispatcher("/location_information.jsp").forward(request, response);
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("vpm")){
		hotelReservation.setEntryId(request.getParameter("btn").substring(4));		
		request.getRequestDispatcher("/promo_information.jsp").forward(request, response);
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("vri")){
		hotelReservation.setEntryId(request.getParameter("btn").substring(4));		
		request.getRequestDispatcher("/room_information.jsp").forward(request, response);
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("ari")){
		hotelReservation.setEntryId(request.getParameter("btn").substring(4));
		request.getRequestDispatcher("/add_room_information.jsp").forward(request, response);
	} else if(request.getParameter("btn")!=null && request.getParameter("btn").startsWith("apm")){
		hotelReservation.setEntryId(request.getParameter("btn").substring(4));		
		request.getRequestDispatcher("/add_promo.jsp").forward(request, response);
	}
	
	hotelReservation.clearTableData();
	hotelReservation.getHotelList();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\t<h1>Hotel Accommodation System</h1>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"accommodation\">Accommodation</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"sightsandactivities\">Sights and Activities</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"planyourvisit\">Plan Your Visit</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"btn\" value=\"contactus\">Contact Us</button>\r\n");
      out.write("\t\t\t");

				if(hotelReservation.getLoggedIn().equals("")){
			
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"adminback\">Back</button>\r\n");
      out.write("\t\t\t");

				} else{
			
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"addnewhotel\">Add New Hotel</button>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" name=\"btn\" value=\"logout\">Log Out</button>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"Controller\">\r\n");
      out.write("\t\t\t<table border=\"2\" cellpadding=\"3\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");
if(!hotelReservation.getLoggedIn().equals("")){
      out.write("<th>#</th>");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>Hotel Name</th>\r\n");
      out.write("\t\t\t\t\t<th>Location</th>\r\n");
      out.write("\t\t\t\t\t<th>Route From</th>\r\n");
      out.write("\t\t\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"4\">");
      out.print(headerVal );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
 
					for(int i = 0; i<hotelReservation.getHotelName().size(); i++){
						int entryId = hotelReservation.getHotelId().get(i);
						String hotelName = hotelReservation.getHotelName().get(i);
						String location = hotelReservation.getLocation().get(i);
						String routeFrom = hotelReservation.getRouteFrom().get(i);
						String description = hotelReservation.getDescription().get(i);
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");
if(!hotelReservation.getLoggedIn().equals("")){
      out.write("<td><input type=\"checkbox\" name=\"check\" value=\"");
      out.print(entryId);
      out.write("\"/></td>");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(hotelName );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(location );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(routeFrom );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(description );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t");

							if(hotelReservation.getLoggedIn().equals("")){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"vhl ");
      out.print(entryId );
      out.write("\">View Location</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"vpm ");
      out.print(entryId );
      out.write("\">View Promos</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"vri ");
      out.print(entryId );
      out.write("\">View Room Information</button></td>\r\n");
      out.write("\t\t\t\t\t\t");

							} else{
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"ari ");
      out.print(entryId );
      out.write("\" style=\"width:100%;\">Add Room</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"submit\" name=\"btn\" value=\"apm ");
      out.print(entryId );
      out.write("\"  style=\"width:100%;\">Add Promo</button></td>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
if(!hotelReservation.getLoggedIn().equals("")){
      out.write("<button type=\"submit\" name=\"btn\" value=\"remove\">Delete Hotel(s)</button>");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
